### PR TITLE
2.6.0.1 - No Arch Build

### PR DESCRIPTION
**Pull request by swainn**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by swainn** [comment]
@snowman2 this one needs to be updated as well.

**Comment by swainn** [comment]
I agree to be a maintainer.

**Comment by swainn** [comment]
@snowman2, this should be ready to merge.

**Comment by snowman2** [comment]
Thanks!

**Pull request merged**
